/*
 * generated by Xtext 2.35.0
 */
package mdu.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class LibraryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mdu.mydsl.MyDsl.Library");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLibraryAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLibraryKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cBooksKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cBooksAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cBooksBookParserRuleCall_4_2_0 = (RuleCall)cBooksAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cBooksAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cBooksBookParserRuleCall_4_3_1_0 = (RuleCall)cBooksAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cMembersKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cMembersAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cMembersMemberParserRuleCall_5_2_0 = (RuleCall)cMembersAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cMembersAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cMembersMemberParserRuleCall_5_3_1_0 = (RuleCall)cMembersAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cLoansKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cLoansAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cLoansLoanParserRuleCall_6_2_0 = (RuleCall)cLoansAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cLoansAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cLoansLoanParserRuleCall_6_3_1_0 = (RuleCall)cLoansAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Library returns Library:
		//    {Library}
		//    'Library'
		//    name=EString
		//    '{'
		//        ('books' '{' books+=Book ( "," books+=Book)* '}' )?
		//        ('members' '{' members+=Member ( "," members+=Member)* '}' )?
		//        ('loans' '{' loans+=Loan ( "," loans+=Loan)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Library}
		//'Library'
		//name=EString
		//'{'
		//    ('books' '{' books+=Book ( "," books+=Book)* '}' )?
		//    ('members' '{' members+=Member ( "," members+=Member)* '}' )?
		//    ('loans' '{' loans+=Loan ( "," loans+=Loan)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Library}
		public Action getLibraryAction_0() { return cLibraryAction_0; }
		
		//'Library'
		public Keyword getLibraryKeyword_1() { return cLibraryKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('books' '{' books+=Book ( "," books+=Book)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'books'
		public Keyword getBooksKeyword_4_0() { return cBooksKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//books+=Book
		public Assignment getBooksAssignment_4_2() { return cBooksAssignment_4_2; }
		
		//Book
		public RuleCall getBooksBookParserRuleCall_4_2_0() { return cBooksBookParserRuleCall_4_2_0; }
		
		//( "," books+=Book)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//books+=Book
		public Assignment getBooksAssignment_4_3_1() { return cBooksAssignment_4_3_1; }
		
		//Book
		public RuleCall getBooksBookParserRuleCall_4_3_1_0() { return cBooksBookParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('members' '{' members+=Member ( "," members+=Member)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'members'
		public Keyword getMembersKeyword_5_0() { return cMembersKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//members+=Member
		public Assignment getMembersAssignment_5_2() { return cMembersAssignment_5_2; }
		
		//Member
		public RuleCall getMembersMemberParserRuleCall_5_2_0() { return cMembersMemberParserRuleCall_5_2_0; }
		
		//( "," members+=Member)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//members+=Member
		public Assignment getMembersAssignment_5_3_1() { return cMembersAssignment_5_3_1; }
		
		//Member
		public RuleCall getMembersMemberParserRuleCall_5_3_1_0() { return cMembersMemberParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('loans' '{' loans+=Loan ( "," loans+=Loan)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'loans'
		public Keyword getLoansKeyword_6_0() { return cLoansKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//loans+=Loan
		public Assignment getLoansAssignment_6_2() { return cLoansAssignment_6_2; }
		
		//Loan
		public RuleCall getLoansLoanParserRuleCall_6_2_0() { return cLoansLoanParserRuleCall_6_2_0; }
		
		//( "," loans+=Loan)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//loans+=Loan
		public Assignment getLoansAssignment_6_3_1() { return cLoansAssignment_6_3_1; }
		
		//Loan
		public RuleCall getLoansLoanParserRuleCall_6_3_1_0() { return cLoansLoanParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class BookElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mdu.mydsl.MyDsl.Book");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBookKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIsbnAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIsbnEStringParserRuleCall_1_0 = (RuleCall)cIsbnAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameEStringParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAuthorKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAuthorAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAuthorEStringParserRuleCall_5_1_0 = (RuleCall)cAuthorAssignment_5_1.eContents().get(0);
		private final Keyword cAvailableKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cAvailableAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAvailableEBooleanParserRuleCall_7_0 = (RuleCall)cAvailableAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Book returns Book:
		//    'Book'
		//    isbn=EString
		//    '{'
		//        'name' name=EString
		//        ('author' author=EString)?
		//        'available' available=EBoolean
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Book'
		//isbn=EString
		//'{'
		//    'name' name=EString
		//    ('author' author=EString)?
		//    'available' available=EBoolean
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Book'
		public Keyword getBookKeyword_0() { return cBookKeyword_0; }
		
		//isbn=EString
		public Assignment getIsbnAssignment_1() { return cIsbnAssignment_1; }
		
		//EString
		public RuleCall getIsbnEStringParserRuleCall_1_0() { return cIsbnEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'name'
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }
		
		//name=EString
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_4_0() { return cNameEStringParserRuleCall_4_0; }
		
		//('author' author=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'author'
		public Keyword getAuthorKeyword_5_0() { return cAuthorKeyword_5_0; }
		
		//author=EString
		public Assignment getAuthorAssignment_5_1() { return cAuthorAssignment_5_1; }
		
		//EString
		public RuleCall getAuthorEStringParserRuleCall_5_1_0() { return cAuthorEStringParserRuleCall_5_1_0; }
		
		//'available'
		public Keyword getAvailableKeyword_6() { return cAvailableKeyword_6; }
		
		//available=EBoolean
		public Assignment getAvailableAssignment_7() { return cAvailableAssignment_7; }
		
		//EBoolean
		public RuleCall getAvailableEBooleanParserRuleCall_7_0() { return cAvailableEBooleanParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class MemberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mdu.mydsl.MyDsl.Member");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMemberKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMemberIdKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMemberIdAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMemberIdEStringParserRuleCall_4_0 = (RuleCall)cMemberIdAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLoansKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cLoansAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cLoansLoanCrossReference_5_2_0 = (CrossReference)cLoansAssignment_5_2.eContents().get(0);
		private final RuleCall cLoansLoanEStringParserRuleCall_5_2_0_1 = (RuleCall)cLoansLoanCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cLoansAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cLoansLoanCrossReference_5_3_1_0 = (CrossReference)cLoansAssignment_5_3_1.eContents().get(0);
		private final RuleCall cLoansLoanEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cLoansLoanCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Member returns Member:
		//    'Member'
		//    name=EString
		//    '{'
		//        'memberId' memberId=EString
		//        ('loans' '(' loans+=[Loan|EString] ( "," loans+=[Loan|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Member'
		//name=EString
		//'{'
		//    'memberId' memberId=EString
		//    ('loans' '(' loans+=[Loan|EString] ( "," loans+=[Loan|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Member'
		public Keyword getMemberKeyword_0() { return cMemberKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'memberId'
		public Keyword getMemberIdKeyword_3() { return cMemberIdKeyword_3; }
		
		//memberId=EString
		public Assignment getMemberIdAssignment_4() { return cMemberIdAssignment_4; }
		
		//EString
		public RuleCall getMemberIdEStringParserRuleCall_4_0() { return cMemberIdEStringParserRuleCall_4_0; }
		
		//('loans' '(' loans+=[Loan|EString] ( "," loans+=[Loan|EString])* ')' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'loans'
		public Keyword getLoansKeyword_5_0() { return cLoansKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//loans+=[Loan|EString]
		public Assignment getLoansAssignment_5_2() { return cLoansAssignment_5_2; }
		
		//[Loan|EString]
		public CrossReference getLoansLoanCrossReference_5_2_0() { return cLoansLoanCrossReference_5_2_0; }
		
		//EString
		public RuleCall getLoansLoanEStringParserRuleCall_5_2_0_1() { return cLoansLoanEStringParserRuleCall_5_2_0_1; }
		
		//( "," loans+=[Loan|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//loans+=[Loan|EString]
		public Assignment getLoansAssignment_5_3_1() { return cLoansAssignment_5_3_1; }
		
		//[Loan|EString]
		public CrossReference getLoansLoanCrossReference_5_3_1_0() { return cLoansLoanCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getLoansLoanEStringParserRuleCall_5_3_1_0_1() { return cLoansLoanEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class LoanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mdu.mydsl.MyDsl.Loan");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoanKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLoanDateKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLoanDateAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLoanDateEStringParserRuleCall_3_0 = (RuleCall)cLoanDateAssignment_3.eContents().get(0);
		private final Keyword cDueDateKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDueDateAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDueDateEStringParserRuleCall_5_0 = (RuleCall)cDueDateAssignment_5.eContents().get(0);
		private final Keyword cBookKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cBookAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cBookBookCrossReference_7_0 = (CrossReference)cBookAssignment_7.eContents().get(0);
		private final RuleCall cBookBookEStringParserRuleCall_7_0_1 = (RuleCall)cBookBookCrossReference_7_0.eContents().get(1);
		private final Keyword cBorrowerKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cBorrowerAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cBorrowerMemberCrossReference_9_0 = (CrossReference)cBorrowerAssignment_9.eContents().get(0);
		private final RuleCall cBorrowerMemberEStringParserRuleCall_9_0_1 = (RuleCall)cBorrowerMemberCrossReference_9_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Loan returns Loan:
		//    'Loan'
		//    '{'
		//        'loanDate' loanDate=EString
		//        'dueDate' dueDate=EString
		//        'book' book=[Book|EString]
		//        'borrower' borrower=[Member|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Loan'
		//'{'
		//    'loanDate' loanDate=EString
		//    'dueDate' dueDate=EString
		//    'book' book=[Book|EString]
		//    'borrower' borrower=[Member|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Loan'
		public Keyword getLoanKeyword_0() { return cLoanKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'loanDate'
		public Keyword getLoanDateKeyword_2() { return cLoanDateKeyword_2; }
		
		//loanDate=EString
		public Assignment getLoanDateAssignment_3() { return cLoanDateAssignment_3; }
		
		//EString
		public RuleCall getLoanDateEStringParserRuleCall_3_0() { return cLoanDateEStringParserRuleCall_3_0; }
		
		//'dueDate'
		public Keyword getDueDateKeyword_4() { return cDueDateKeyword_4; }
		
		//dueDate=EString
		public Assignment getDueDateAssignment_5() { return cDueDateAssignment_5; }
		
		//EString
		public RuleCall getDueDateEStringParserRuleCall_5_0() { return cDueDateEStringParserRuleCall_5_0; }
		
		//'book'
		public Keyword getBookKeyword_6() { return cBookKeyword_6; }
		
		//book=[Book|EString]
		public Assignment getBookAssignment_7() { return cBookAssignment_7; }
		
		//[Book|EString]
		public CrossReference getBookBookCrossReference_7_0() { return cBookBookCrossReference_7_0; }
		
		//EString
		public RuleCall getBookBookEStringParserRuleCall_7_0_1() { return cBookBookEStringParserRuleCall_7_0_1; }
		
		//'borrower'
		public Keyword getBorrowerKeyword_8() { return cBorrowerKeyword_8; }
		
		//borrower=[Member|EString]
		public Assignment getBorrowerAssignment_9() { return cBorrowerAssignment_9; }
		
		//[Member|EString]
		public CrossReference getBorrowerMemberCrossReference_9_0() { return cBorrowerMemberCrossReference_9_0; }
		
		//EString
		public RuleCall getBorrowerMemberEStringParserRuleCall_9_0_1() { return cBorrowerMemberEStringParserRuleCall_9_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mdu.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mdu.mydsl.MyDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	
	private final LibraryElements pLibrary;
	private final BookElements pBook;
	private final MemberElements pMember;
	private final LoanElements pLoan;
	private final EStringElements pEString;
	private final EBooleanElements pEBoolean;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pLibrary = new LibraryElements();
		this.pBook = new BookElements();
		this.pMember = new MemberElements();
		this.pLoan = new LoanElements();
		this.pEString = new EStringElements();
		this.pEBoolean = new EBooleanElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("mdu.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Library returns Library:
	//    {Library}
	//    'Library'
	//    name=EString
	//    '{'
	//        ('books' '{' books+=Book ( "," books+=Book)* '}' )?
	//        ('members' '{' members+=Member ( "," members+=Member)* '}' )?
	//        ('loans' '{' loans+=Loan ( "," loans+=Loan)* '}' )?
	//    '}';
	public LibraryElements getLibraryAccess() {
		return pLibrary;
	}
	
	public ParserRule getLibraryRule() {
		return getLibraryAccess().getRule();
	}
	
	//Book returns Book:
	//    'Book'
	//    isbn=EString
	//    '{'
	//        'name' name=EString
	//        ('author' author=EString)?
	//        'available' available=EBoolean
	//    '}';
	public BookElements getBookAccess() {
		return pBook;
	}
	
	public ParserRule getBookRule() {
		return getBookAccess().getRule();
	}
	
	//Member returns Member:
	//    'Member'
	//    name=EString
	//    '{'
	//        'memberId' memberId=EString
	//        ('loans' '(' loans+=[Loan|EString] ( "," loans+=[Loan|EString])* ')' )?
	//    '}';
	public MemberElements getMemberAccess() {
		return pMember;
	}
	
	public ParserRule getMemberRule() {
		return getMemberAccess().getRule();
	}
	
	//Loan returns Loan:
	//    'Loan'
	//    '{'
	//        'loanDate' loanDate=EString
	//        'dueDate' dueDate=EString
	//        'book' book=[Book|EString]
	//        'borrower' borrower=[Member|EString]
	//    '}';
	public LoanElements getLoanAccess() {
		return pLoan;
	}
	
	public ParserRule getLoanRule() {
		return getLoanAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
